# fly.toml app configuration file generated for facetime-v5 on 2025-06-16T17:14:58-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'facetime-v5'
primary_region = 'den'

[build]
dockerfile = 'docker/Dockerfile.fly'

[deploy]
strategy = 'rolling'

[[services]]
protocol = 'udp'
internal_port = 8039

[[services.ports]]
port = 8039

[[services]]
protocol = 'tcp'
internal_port = 8040

[[services.ports]]
port = 8040

[[vm]]
memory = '1gb'
cpu_kind = 'shared'
cpus = 1
