[package]
name = "server"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "server"

[dependencies]
log = "0.4.27"
tokio = { version = "1.45.1", features = ["full"] }
shared = { path = "../shared" }
env_logger = "0.11.8"
clap = { version = "4.5.40", features = ["derive"] }
