name: Deploy WeSFU

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Full Docker Cleanup (Before Build)
        run: |
          echo "Stopping and removing all containers..."
          docker ps -aq | xargs -r docker stop
          docker ps -aq | xargs -r docker rm

          echo "Removing all images..."
          docker images -aq | xargs -r docker rmi -f

          echo "Removing all volumes..."
          docker volume ls -q | xargs -r docker volume rm

          echo "Removing all networks..."
          docker network ls --filter 'type=custom' -q | xargs -r docker network rm

          echo "Pruning system (dangling data)..."
          docker system prune -af --volumes

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker Image
        run: |
          docker build -f docker/Dockerfile.aws -t wesfu-server:latest .

      - name: Create Custom Docker Network with MTU 9001
        run: |
          docker network create \
            --driver=bridge \
            --opt com.docker.network.driver.mtu=9001 \
            wesfu-net

      - name: Run New Container
        run: |
          docker run -d \
            --name wesfu-server \
            --network wesfu-net \
            -p 8040:8040 \
            -p 8039:8039/udp \
            wesfu-server:latest

      - name: Final Docker Prune (Clean Everything Not In Use)
        run: |
          echo "Pruning unused images, containers, volumes, and networks..."
          docker system prune -af --volumes
